title: Interview Docs
tagline : Interview questions and answers
description: Interview questions and answers notes or docs
# baseurl: "/interview-docs" # the subpath of your site, e.g. /blog
baseurl: ""
url: https://interview-docs.codewithmit.com # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Mit Patel
  email: patelzeelu15@gmail.com
  github: mitpatel2710

production_url: https://interview-docs.codewithmit.com

# Include additional directories to be processed by Jekyll
include: ["_pages"]

# Set a path/url to a logo that will be displayed instead of the title
#logo: "/utils/job-logo.jpeg"

remote_theme: pmarsceill/just-the-docs
# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

theme: jekyll-theme-minimal

# Split pages into sections that can
