title: Interview Docs
baseurl: "/interview-docs"  # GitHub Pages subdirectory
url: "https://Mitpatel2710.github.io"

# Ensure Jekyll processes Markdown files
markdown: kramdown
kramdown:
  input: GFM

# Include folders to be processed by Jekyll
include:
  - "_pages"
  - "docs"

# Disable Jekyll's default ignore behavior
exclude:
  - ".idea"
  - "venv"
  - ".DS_Store"

# Navigation Settings
nav:
  - title: "Java"
    url: "{{ site.baseurl }}/docs/java/java-basics"
  - title: "AWS"
    url: "{{ site.baseurl }}/docs/aws/aws-intro"
  - title: "Database"
    url: "{{ site.baseurl }}/docs/database/sql"
  - title: "System Design"
    url: "{{ site.baseurl }}/docs/system-design/architecture"
  - title: "DevOps"
    url: "{{ site.baseurl }}/docs/devops/docker"
  - title: "Microservices"
    url: "{{ site.baseurl }}/docs/microservices/microservices"
