title: Interview Docs
tagline: Interview questions and answers
description: Interview questions and answers notes or docs

# Correct base URL for GitHub Pages
baseurl: "/interviewdocs"
url: "https://Mitpatel2710.github.io"

author:
  name: Mit Patel
  email: patelzeelu15@gmail.com
  github: mitpatel2710

production_url: "https://Mitpatel2710.github.io/interviewdocs"

# GitHub Pages theme setup
remote_theme: pmarsceill/just-the-docs
color_scheme: light

# Enable search functionality
search_enabled: true
search:
  heading_level: 6
  previews: 10
  rel_url: true
  button: true

# Navigation settings
nav:
  - title: "Java"
    url: "{{ site.baseurl }}/docs/java/index.html"
  - title: "AWS"
    url: "{{ site.baseurl }}/docs/aws/index.html"
  - title: "Database"
    url: "{{ site.baseurl }}/docs/database/index.html"
  - title: "System Design"
    url: "{{ site.baseurl }}/docs/system-design/index.html"
  - title: "DevOps"
    url: "{{ site.baseurl }}/docs/devops/index.html"
  - title: "Microservices"
    url: "{{ site.baseurl }}/docs/microservices/index.html"

# Ensure additional directories and files are processed
include:
  - "_pages"
  - ".nojekyll"
